In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.Series([10,20,30,40])
print(ds)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
dss=pd.Series((10,20,30,40))
print(dss)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
ds=pd.Series([10,20,30,40],index=['A','B','C','D'])
print(ds)

A    10
B    20
C    30
D    40
dtype: int64

In [5]:
ds=pd.Series({'A':10,'B':20,'C':30,'D':40})
print(ds)

A    10
B    20
C    30
D    40
dtype: int64

In [6]:
ds=pd.Series(range(1,10))
print(ds)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [7]:
ds=pd.Series(np.array([10,20,30]))
print(ds)

0    10
1    20
2    30
dtype: int64

In [8]:
ds=pd.Series(np.array(range(1,10)))
print(ds)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [9]:
print(type(ds))

<class 'pandas.core.series.Series'>

In [10]:
ds=pd.DataFrame([['V','H','A'],[10,20,30],[1,2,3]])
print(ds)

    0   1   2
0   V   H   A
1  10  20  30
2   1   2   3

In [11]:
ds=pd.DataFrame([['V','H','A'],[10,20,30],[1,2,3]],index=['A','B','C'],columns=['P','Q','R'])
print(ds)

    P   Q   R
A   V   H   A
B  10  20  30
C   1   2   3

In [12]:
ds=pd.DataFrame({'P':['V','H','A'],'Q':[10,20,30],'R':[1,2,3]},index=['A','B','C'])
print(ds)

   P   Q  R
A  V  10  1
B  H  20  2
C  A  30  3

In [13]:
ds=pd.DataFrame({'P':['V','H','A'],'Q':[10,20,30],'R':[1,2,3]},index=['A','B','C'],columns=['X','Y','Z'])
print(ds)

     X    Y    Z
A  NaN  NaN  NaN
B  NaN  NaN  NaN
C  NaN  NaN  NaN

In [14]:
ds=pd.DataFrame(np.array([['V','H','A'],[10,20,30],[1,2,3]]))
print(ds)

    0   1   2
0   V   H   A
1  10  20  30
2   1   2   3

In [15]:
df=pd.DataFrame([{'A':10,'B':20},{'C':30,'D':40},{'E':50,'F':60}])
print(df)

      A     B     C     D     E     F
0  10.0  20.0   NaN   NaN   NaN   NaN
1   NaN   NaN  30.0  40.0   NaN   NaN
2   NaN   NaN   NaN   NaN  50.0  60.0

In [16]:
df=pd.DataFrame([{'A':10,'B':20},{'A':30,'B':40},{'A':50,'B':60}])
print(df)

    A   B
0  10  20
1  30  40
2  50  60

In [17]:
df=pd.DataFrame([{'Subject':'Python','Fac':'VHA','Marks':10},{'Subject':'FSD','Fac':'PSP','Marks':9},
                 {'Subject':'COA','Fac':'VBY','Marks':10},{'Subject':'TOC','Fac':'DPS','Marks':9},
                {'Subject':'DM','Fac':'MSS','Marks':9}])
print(df)

  Subject  Fac  Marks
0  Python  VHA     10
1     FSD  PSP      9
2     COA  VBY     10
3     TOC  DPS      9
4      DM  MSS      9

In [18]:
df.set_index('Subject')

         Fac  Marks
Subject
Python   VHA     10
FSD      PSP      9
COA      VBY     10
TOC      DPS      9
DM       MSS      9

In [19]:
df.set_index('Subject',drop=True)

         Fac  Marks
Subject
Python   VHA     10
FSD      PSP      9
COA      VBY     10
TOC      DPS      9
DM       MSS      9

In [20]:
df.set_index('Subject',drop=False)

        Subject  Fac  Marks
Subject
Python   Python  VHA     10
FSD         FSD  PSP      9
COA         COA  VBY     10
TOC         TOC  DPS      9
DM           DM  MSS      9

In [21]:
df=df.set_index('Subject')
print(df)
# df.reset_index()

         Fac  Marks
Subject
Python   VHA     10
FSD      PSP      9
COA      VBY     10
TOC      DPS      9
DM       MSS      9

In [22]:
df.loc['FSD','Fac']

'PSP'

In [23]:
df.loc['FSD','Fac']='NAS'

In [24]:
df

         Fac  Marks
Subject
Python   VHA     10
FSD      NAS      9
COA      VBY     10
TOC      DPS      9
DM       MSS      9

In [25]:
df.loc['FSD','Marks']=10
df

         Fac  Marks
Subject
Python   VHA     10
FSD      NAS     10
COA      VBY     10
TOC      DPS      9
DM       MSS      9

In [26]:
df.loc['Project']=['VHA',10]
# adding row

In [27]:
df

         Fac  Marks
Subject
Python   VHA     10
FSD      NAS     10
COA      VBY     10
TOC      DPS      9
DM       MSS      9
Project  VHA     10

In [28]:
df["HOD"]="MJT"
df
# adding column

         Fac  Marks  HOD
Subject
Python   VHA     10  MJT
FSD      NAS     10  MJT
COA      VBY     10  MJT
TOC      DPS      9  MJT
DM       MSS      9  MJT
Project  VHA     10  MJT

In [29]:
df['New']=df['Marks']*10

In [30]:
df

         Fac  Marks  HOD  New
Subject
Python   VHA     10  MJT  100
FSD      NAS     10  MJT  100
COA      VBY     10  MJT  100
TOC      DPS      9  MJT   90
DM       MSS      9  MJT   90
Project  VHA     10  MJT  100

In [31]:
arr=np.random.randint(1,100,(8,5))
df=pd.DataFrame(arr,columns=['A','B','C','D','E'])
df

    A   B   C   D   E
0  34  74  99   6  35
1  82  67  97  83  15
2  84  64  31  84  83
3  21  45  71  89  35
4  36  11  43  17  96
5  65   2  77  87  95
6  29  44   2  51  58
7  92  44  45  75  61

In [32]:
print("Shape:",df.shape)
print("Size:",df.size)
print("Dimension:",df.ndim)

Shape: (8, 5)
Size: 40
Dimension: 2

In [33]:
df["Sum"]=df['A']+df['B']+df['C']+df['D']+df['E']
df

    A   B   C   D   E  Sum
0  34  74  99   6  35  248
1  82  67  97  83  15  344
2  84  64  31  84  83  346
3  21  45  71  89  35  261
4  36  11  43  17  96  203
5  65   2  77  87  95  326
6  29  44   2  51  58  184
7  92  44  45  75  61  317

In [34]:
df.loc[6,'C']=89
df

    A   B   C   D   E  Sum
0  34  74  99   6  35  248
1  82  67  97  83  15  344
2  84  64  31  84  83  346
3  21  45  71  89  35  261
4  36  11  43  17  96  203
5  65   2  77  87  95  326
6  29  44  89  51  58  184
7  92  44  45  75  61  317

In [35]:
df.iloc[6:7,2:3]=98
df

    A   B   C   D   E  Sum
0  34  74  99   6  35  248
1  82  67  97  83  15  344
2  84  64  31  84  83  346
3  21  45  71  89  35  261
4  36  11  43  17  96  203
5  65   2  77  87  95  326
6  29  44  98  51  58  184
7  92  44  45  75  61  317

In [36]:
df.iloc[2::,1:4]

    B   C   D
2  64  31  84
3  45  71  89
4  11  43  17
5   2  77  87
6  44  98  51
7  44  45  75

In [37]:
df.loc['New']=[77,88,99,90,78,56]
df

      A   B   C   D   E  Sum
0    34  74  99   6  35  248
1    82  67  97  83  15  344
2    84  64  31  84  83  346
3    21  45  71  89  35  261
4    36  11  43  17  96  203
5    65   2  77  87  95  326
6    29  44  98  51  58  184
7    92  44  45  75  61  317
New  77  88  99  90  78   56

In [38]:
uc=pd.DataFrame({"CourseID":[1,2,3,4,5],'CourseName':['Python','FSD','TOC','DM','COA'],
                  'Credits':[6,5,4,3,3],'Faculty':['VHA','PSP','DPS','MSS','VPY']})
uc

   CourseID CourseName  Credits Faculty
0         1     Python        6     VHA
1         2        FSD        5     PSP
2         3        TOC        4     DPS
3         4         DM        3     MSS
4         5        COA        3     VPY

In [39]:
uc=uc.set_index('CourseID')
uc

         CourseName  Credits Faculty
CourseID
1            Python        6     VHA
2               FSD        5     PSP
3               TOC        4     DPS
4                DM        3     MSS
5               COA        3     VPY

In [40]:
uc['Semester']=4
uc

         CourseName  Credits Faculty  Semester
CourseID
1            Python        6     VHA         4
2               FSD        5     PSP         4
3               TOC        4     DPS         4
4                DM        3     MSS         4
5               COA        3     VPY         4

In [41]:
uc.iloc[1:2,1:2]=6
uc

         CourseName  Credits Faculty  Semester
CourseID
1            Python        6     VHA         4
2               FSD        6     PSP         4
3               TOC        4     DPS         4
4                DM        3     MSS         4
5               COA        3     VPY         4

In [42]:
uc.loc['New']=["XYZ",0,"ABC",4]

In [43]:
uc

         CourseName  Credits Faculty  Semester
CourseID
1            Python        6     VHA         4
2               FSD        6     PSP         4
3               TOC        4     DPS         4
4                DM        3     MSS         4
5               COA        3     VPY         4
New             XYZ        0     ABC         4