In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [72]:
df=pd.read_csv("social_media_engagement.csv")
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [73]:
dff=pd.DataFrame(np.random.randint(1,100,(20,5)),columns=["A","B","C","D","E"])
dff

     A   B   C   D   E
0   51  10  18  91  22
1    9  62  85  12  17
2   33  28  48  55  24
3   91  18   7  13  80
4   77  72  99  26  46
5   67  46  66   6  85
6   57  91  85  56  18
7   23  58  71  16  63
8   43  68  54  68  36
9   97   6  64  30  36
10  41  69  85  19  20
11  19  63  31  80  62
12  48  93  89  89  61
13  10  68  77  38  71
14  32  16  89  23   1
15  55  46  89   8  99
16  69  15  33  19  49
17   9  19  86   9  63
18  90  97  41  91  65
19  65  51  50  87  57

In [74]:
dff.apply(sum)

A     986
B     996
C    1267
D     836
E     975
dtype: int64

In [75]:
dff.apply("mean")

A    49.30
B    49.80
C    63.35
D    41.80
E    48.75
dtype: float64

In [76]:
dff.apply(sum,axis=1)

0     192
1     185
2     188
3     209
4     320
5     270
6     307
7     231
8     269
9     233
10    234
11    255
12    380
13    264
14    161
15    297
16    185
17    186
18    384
19    310
dtype: int64

In [77]:
dff.apply(["mean","sum"])

          A      B        C      D       E
mean   49.3   49.8    63.35   41.8   48.75
sum   986.0  996.0  1267.00  836.0  975.00

In [78]:
dff.apply(["mean","sum"],axis=1)

    mean    sum
0   38.4  192.0
1   37.0  185.0
2   37.6  188.0
3   41.8  209.0
4   64.0  320.0
5   54.0  270.0
6   61.4  307.0
7   46.2  231.0
8   53.8  269.0
9   46.6  233.0
10  46.8  234.0
11  51.0  255.0
12  76.0  380.0
13  52.8  264.0
14  32.2  161.0
15  59.4  297.0
16  37.0  185.0
17  37.2  186.0
18  76.8  384.0
19  62.0  310.0

In [79]:
dff.apply(lambda x:x["A"]+x["B"]+x["C"],axis=1)

0      79
1     156
2     109
3     116
4     248
5     179
6     233
7     152
8     165
9     167
10    195
11    113
12    230
13    155
14    137
15    190
16    117
17    114
18    228
19    166
dtype: int32

In [80]:
dff["Total"]=dff.apply(sum,axis=1)
dff

     A   B   C   D   E  Total
0   51  10  18  91  22    192
1    9  62  85  12  17    185
2   33  28  48  55  24    188
3   91  18   7  13  80    209
4   77  72  99  26  46    320
5   67  46  66   6  85    270
6   57  91  85  56  18    307
7   23  58  71  16  63    231
8   43  68  54  68  36    269
9   97   6  64  30  36    233
10  41  69  85  19  20    234
11  19  63  31  80  62    255
12  48  93  89  89  61    380
13  10  68  77  38  71    264
14  32  16  89  23   1    161
15  55  46  89   8  99    297
16  69  15  33  19  49    185
17   9  19  86   9  63    186
18  90  97  41  91  65    384
19  65  51  50  87  57    310

In [81]:
def grade(x):
    if x>300:
        return "A+"
    elif x>250:
        return "A"
    elif x>200:
        return "B+"
    elif x>150:
        return "B"
    else:
        return "F"

In [82]:
dff["Grade"]=dff["Total"].apply(grade)
dff

     A   B   C   D   E  Total Grade
0   51  10  18  91  22    192     B
1    9  62  85  12  17    185     B
2   33  28  48  55  24    188     B
3   91  18   7  13  80    209    B+
4   77  72  99  26  46    320    A+
5   67  46  66   6  85    270     A
6   57  91  85  56  18    307    A+
7   23  58  71  16  63    231    B+
8   43  68  54  68  36    269     A
9   97   6  64  30  36    233    B+
10  41  69  85  19  20    234    B+
11  19  63  31  80  62    255     A
12  48  93  89  89  61    380    A+
13  10  68  77  38  71    264     A
14  32  16  89  23   1    161     B
15  55  46  89   8  99    297     A
16  69  15  33  19  49    185     B
17   9  19  86   9  63    186     B
18  90  97  41  91  65    384    A+
19  65  51  50  87  57    310    A+

In [83]:
def result(x):
    if x["A"]>=35 and x["B"]>=35 and x["C"]>=35 and x["D"]>=35 and x["E"]>=35:
        return "Pass"
    else:
        return "Fail"

In [84]:
dff["Result"]=dff.apply(result,axis=1)
dff

     A   B   C   D   E  Total Grade Result
0   51  10  18  91  22    192     B   Fail
1    9  62  85  12  17    185     B   Fail
2   33  28  48  55  24    188     B   Fail
3   91  18   7  13  80    209    B+   Fail
4   77  72  99  26  46    320    A+   Fail
5   67  46  66   6  85    270     A   Fail
6   57  91  85  56  18    307    A+   Fail
7   23  58  71  16  63    231    B+   Fail
8   43  68  54  68  36    269     A   Pass
9   97   6  64  30  36    233    B+   Fail
10  41  69  85  19  20    234    B+   Fail
11  19  63  31  80  62    255     A   Fail
12  48  93  89  89  61    380    A+   Pass
13  10  68  77  38  71    264     A   Fail
14  32  16  89  23   1    161     B   Fail
15  55  46  89   8  99    297     A   Fail
16  69  15  33  19  49    185     B   Fail
17   9  19  86   9  63    186     B   Fail
18  90  97  41  91  65    384    A+   Pass
19  65  51  50  87  57    310    A+   Pass

In [85]:
dff["Result"]=dff.apply(lambda x: "Pass" if (x["A"]>=35 and x["B"]>=35 and x["C"]>=35 and x["D"]>=35 and x["E"]>=35)
                        else "Fail"  ,axis=1)
dff

     A   B   C   D   E  Total Grade Result
0   51  10  18  91  22    192     B   Fail
1    9  62  85  12  17    185     B   Fail
2   33  28  48  55  24    188     B   Fail
3   91  18   7  13  80    209    B+   Fail
4   77  72  99  26  46    320    A+   Fail
5   67  46  66   6  85    270     A   Fail
6   57  91  85  56  18    307    A+   Fail
7   23  58  71  16  63    231    B+   Fail
8   43  68  54  68  36    269     A   Pass
9   97   6  64  30  36    233    B+   Fail
10  41  69  85  19  20    234    B+   Fail
11  19  63  31  80  62    255     A   Fail
12  48  93  89  89  61    380    A+   Pass
13  10  68  77  38  71    264     A   Fail
14  32  16  89  23   1    161     B   Fail
15  55  46  89   8  99    297     A   Fail
16  69  15  33  19  49    185     B   Fail
17   9  19  86   9  63    186     B   Fail
18  90  97  41  91  65    384    A+   Pass
19  65  51  50  87  57    310    A+   Pass

In [86]:
def bonus(x):
    return x+2

In [90]:
dff["Total"].apply(bonus)

0     194
1     187
2     190
3     211
4     322
5     272
6     309
7     233
8     271
9     235
10    236
11    257
12    382
13    266
14    163
15    299
16    187
17    188
18    386
19    312
Name: Total, dtype: int64