In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"A":[5,6],"B":[7,8]})

In [3]:
df1

   A  B
0  1  3
1  2  4

In [4]:
df2

   A  B
0  5  7
1  6  8

In [5]:
pd.concat((df1,df2))

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [6]:
pd.concat((df1,df2),axis=0)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [7]:
pd.concat((df1,df2),axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [8]:
pd.concat((df1,df2),axis=1,ignore_index=True)
# leaves it's own index
# ignores index as per column here

   0  1  2  3
0  1  3  5  7
1  2  4  6  8

In [9]:
pd.concat((df1,df2),axis=0,ignore_index=True)
# leaves it's own index
# False by default
# ignores index as per row here

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [10]:
pd.concat((df1,df2),axis=0,ignore_index=False,keys=["df1","df2"])

       A  B
df1 0  1  3
    1  2  4
df2 0  5  7
    1  6  8

In [11]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,6],"B":[7,8]})

In [12]:
pd.concat((df1,df2))

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [13]:
pd.concat((df1,df2),axis=1)

   A  B  C  B
0  1  3  5  7
1  2  4  6  8

In [14]:
pd.concat((df1,df2),axis=1,sort=True)

   A  B  C  B
0  1  3  5  7
1  2  4  6  8

In [15]:
df1=pd.DataFrame({"A":[1,2,3],"B":[3,4,5]})
df2=pd.DataFrame({"C":[5,6],"B":[7,8]})

In [16]:
pd.concat((df1,df2),axis=1)

   A  B    C    B
0  1  3  5.0  7.0
1  2  4  6.0  8.0
2  3  5  NaN  NaN

In [17]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,6],"B":[7,8]})

In [18]:
pd.concat((df1,df2),join="inner")
# gives only common column of both data frams by concating their values

   B
0  3
1  4
0  7
1  8

In [19]:
pd.concat((df1,df2),join="outer")
# outer is by default, gives union

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [20]:
df1=pd.DataFrame({"D":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,6],"A":[7,8]})

In [21]:
pd.concat((df1,df2),sort=True)
# sorts column names and not the values of dataframe

     A    B    C    D
0  NaN  3.0  NaN  1.0
1  NaN  4.0  NaN  2.0
0  7.0  NaN  5.0  NaN
1  8.0  NaN  6.0  NaN

In [22]:
pd.concat((df1,df2),sort=False)

     D    B    C    A
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [23]:
df1=pd.DataFrame({"name":["vha","psp","vby","mss","dps"],"sub":["python","fsd","coa","dm","toc"],"id":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5],"mark":[9,8,10,8,8]})

In [24]:
df1

  name     sub  id
0  vha  python   3
1  psp     fsd   2
2  vby     coa   1
3  mss      dm   4
4  dps     toc   6

In [25]:
df2

   id  mark
0   1     9
1   2     8
2   3    10
3   4     8
4   5     8

In [26]:
pd.merge(df1,df2,on="id")
# takes only the common value of the entered column
# here df1 has id 6 and df2 has id 5, so those two enteries won't be present while merging

  name     sub  id  mark
0  vha  python   3    10
1  psp     fsd   2     8
2  vby     coa   1     9
3  mss      dm   4     8

In [27]:
pd.merge(df1,df2,on="id",how="inner")

  name     sub  id  mark
0  vha  python   3    10
1  psp     fsd   2     8
2  vby     coa   1     9
3  mss      dm   4     8

In [28]:
pd.merge(df1,df2,on="id",how="outer")

  name     sub  id  mark
0  vha  python   3  10.0
1  psp     fsd   2   8.0
2  vby     coa   1   9.0
3  mss      dm   4   8.0
4  dps     toc   6   NaN
5  NaN     NaN   5   8.0

In [29]:
pd.merge(df1,df2,on="id",how="left")
# all the data of first data frame and common entries of second

  name     sub  id  mark
0  vha  python   3  10.0
1  psp     fsd   2   8.0
2  vby     coa   1   9.0
3  mss      dm   4   8.0
4  dps     toc   6   NaN

In [30]:
pd.merge(df1,df2,on="id",how="right")
# all the data of second data frame and common entries of first

  name     sub  id  mark
0  vby     coa   1     9
1  psp     fsd   2     8
2  vha  python   3    10
3  mss      dm   4     8
4  NaN     NaN   5     8

In [31]:
pd.merge(df1,df2,how="cross")

   name     sub  id_x  id_y  mark
0   vha  python     3     1     9
1   vha  python     3     2     8
2   vha  python     3     3    10
3   vha  python     3     4     8
4   vha  python     3     5     8
5   psp     fsd     2     1     9
6   psp     fsd     2     2     8
7   psp     fsd     2     3    10
8   psp     fsd     2     4     8
9   psp     fsd     2     5     8
10  vby     coa     1     1     9
11  vby     coa     1     2     8
12  vby     coa     1     3    10
13  vby     coa     1     4     8
14  vby     coa     1     5     8
15  mss      dm     4     1     9
16  mss      dm     4     2     8
17  mss      dm     4     3    10
18  mss      dm     4     4     8
19  mss      dm     4     5     8
20  dps     toc     6     1     9
21  dps     toc     6     2     8
22  dps     toc     6     3    10
23  dps     toc     6     4     8
24  dps     toc     6     5     8

In [32]:
# pd.merge(df1,df2,on="id",how="corss")
# it will get confused and give error when we specify column

In [33]:
pd.merge(df1,df2,left_index=True,right_index=True)

  name     sub  id_x  id_y  mark
0  vha  python     3     1     9
1  psp     fsd     2     2     8
2  vby     coa     1     3    10
3  mss      dm     4     4     8
4  dps     toc     6     5     8

In [34]:
pd.merge(df1,df2,left_index=True,right_index=True,suffixes=("_df1","_df2"))

  name     sub  id_df1  id_df2  mark
0  vha  python       3       1     9
1  psp     fsd       2       2     8
2  vby     coa       1       3    10
3  mss      dm       4       4     8
4  dps     toc       6       5     8

In [35]:
df1=pd.DataFrame({"name":["vha","psp","vby","mss","dps"],"sub":["python","fsd","coa","dm","toc"],"in":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5],"mark":[9,8,10,8,8]})

In [36]:
df1.merge(df2,left_on="in",right_on="id")
# only common values will appear

  name     sub  in  id  mark
0  vha  python   3   3    10
1  psp     fsd   2   2     8
2  vby     coa   1   1     9
3  mss      dm   4   4     8

In [37]:
df1=pd.DataFrame({"name":["vha","psp","vby","mss","dps"],"sub":["python","fsd","coa","dm","toc"],"in":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5],"mark":[9,8,10,8,8],"fac":["vha","nas","vby","mss","dps"]})

In [38]:
df1.merge(df2,left_on="name",right_on="fac")

  name     sub  in  id  mark  fac
0  vha  python   3   1     9  vha
1  vby     coa   1   3    10  vby
2  mss      dm   4   4     8  mss
3  dps     toc   6   5     8  dps

In [39]:
df1=pd.DataFrame({"name":["vha","psp","vby","mss","dps"],"sub":["python","fsd","coa","dm","toc"],"id":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5],"mark":[9,8,10,8,8],"fac":["vha","nas","vby","mss","dps"]})

In [40]:
df1.merge(df2,left_on="name",right_on="fac",how="outer",suffixes=("_b1_sem3","_b1_sem4"))

  name     sub  id_b1_sem3  id_b1_sem4  mark  fac
0  vha  python         3.0         1.0   9.0  vha
1  psp     fsd         2.0         NaN   NaN  NaN
2  vby     coa         1.0         3.0  10.0  vby
3  mss      dm         4.0         4.0   8.0  mss
4  dps     toc         6.0         5.0   8.0  dps
5  NaN     NaN         NaN         2.0   8.0  nas